---
title: "DisperseR on Hopper"
author: "Lucas Henneman"
date: "12/06/2021"
output: github_document
---

This repository contains information relevant to running the [disperseR](https://github.com/lhenneman/disperseR) R package on GMU's Hopper cluster. 

# Structure of this repository
This readme describes example code available on this repository and datasets available on Hopper. The Wiki should be used to provide more detail about specific datasets, logistical information about how to run the model, documentation of substantial changes, and lists of publications using disperseR.

# Directories
- `code`
  -  `power_plants_ex`: examples of running disperseR for each power plant in 2019 and 2020, weighting the results by SO2 emissions, using a statistical relationship with 2005 CMAQ-DDM results to convert the raw disperseR results to PM2.5 concentrations.
- `data`
  - `input_datasets`: describes datasets used as inputs to disperseR in our group (these include emissions datasets---other input data such as meteorology data should not be documented)
  - `output_datasets`: describes datasets of disperseR results
- `figures`
  - None yet
